name: "release"
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.14.x
        xgo_version:
          - latest

    steps:
      - name: Set environment
        run: |
          echo "::set-env name=BUILD_TAG::${GITHUB_REF##*/}"
          echo "::set-env name=BUILD_FILE_PREFIX::${GITHUB_REPOSITORY##*/}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.14.x
          dest: build
          prefix: ${{ env.BUILD_FILE_PREFIX }}-${{ env.BUILD_TAG }}
          targets: darwin/amd64,darwin/386,windows/amd64,windows/386,windows/arm64,linux/amd64,linux/386,linux/arm64
          v: true
          x: false
          buildmode: default
          ldflags: -s -w

      - name: Check && chunk
        run: |
          cd build
          ls -al ./
          for file in ./*; do
            zip $file.zip ./$file
          done

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          set -x
          assets=()
          for asset in ./build/*.zip; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -F ".github/lastchange.md" "${BUILD_TAG}"